
// *************************************************************************
// *****   This file is automatically generated by the tool 'gen-ui'   *****
// *************************************************************************
// *****                 ==> DO NOT EDIT THIS FILE <==                 *****
// *************************************************************************

#include <getopt.h>
#include "ui-wdf.h"

//
///////////////////////////////////////////////////////////////////////////////
///////////////                  OptionInfo[]                   ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoOption_t OptionInfo[OPT__N_TOTAL+1] =
{
    {0,0,0,0,0}, // OPT_NONE,

    {	OPT_VERSION, 'V', "version",
	0,
	"Stop parsing the command line, print a version info and exit."
    },

    {	OPT_HELP, 'h', "help",
	0,
	"Stop parsing the command line, print a help message and exit."
    },

    {	OPT_XHELP, 0, "xhelp",
	0,
	"Same as --help."
    },

    {	OPT_PACK, 'P', "pack",
	0,
	"Pack an archive. This is the general default."
    },

    {	OPT_UNPACK, 'U', "unpack",
	0,
	"Unpack an archive.\n"
	"This is the default, when the program name starts with the two"
	" letters 'un' in any case."
    },

    {	OPT_CAT, 'A', "cat",
	0,
	"Concatenate files and print on the standard output. WDF and CISO"
	" files are extracted before printing, all other files are copied byte"
	" by byte.\n"
	"This is the default, when the program namecontains the three letter"
	" 'cat' in any case."
    },

    {	OPT_CMP, 'M', "cmp",
	0,
	"Enter compare mode and ignore all (un-)packing options.\n"
	"Two source files are compared. If --dest or --DEST is set, than all"
	" source files are compared against files in the destination path. If"
	" the second source file is mising then stdin is used instead.\n"
	"This is the default, when the program namecontains the letters 'cmp'"
	" or 'diff' in any case."
    },

    {	OPT_DUMP, 'X', "dump",
	0,
	"Dump the data structure of all archives and ignore non WDF and non"
	" CISO files. All packing, unpacking and compare options are ignored.\n"
	"This is the default, when the program contains the sub string 'dump'"
	" in any case."
    },

    {	OPT_WDF, 'W', "wdf",
	0,
	"Force WDF output mode if compressing and set the default suffix to"
	" '.wdf'. This is the general default."
    },

    {	OPT_CISO, 'C', "ciso",
	0,
	"Force CISO output mode if compressing and set the default suffix to"
	" '.ciso'.\n"
	" This is the default, when the program name contains the sub string"
	" 'ciso' in any case."
    },

    {	OPT_WBI, 0, "wbi",
	0,
	"Force CISO output mode if compressing and set the default suffix to"
	" '.wbi'.\n"
	" This is the default, when the program name contains the sub string"
	" 'wbi' but not 'ciso' in any case."
    },

    {	OPT_SUFFIX, 's', "suffix",
	".suf",
	"Use suffix '.suf' instead of '.wdf' or '.ciso' for packed files."
    },

    {	OPT_DEST, 'd', "dest",
	"path",
	"Define a destination path (directory/file). The destination path is"
	" scanned for escape sequences (see option --esc) to allow generic"
	" pathes."
    },

    {	OPT_DEST2, 'D', "DEST",
	"path",
	"Like --dest, but create the directory path automatically."
    },

    {	OPT_PRESERVE, 'p', "preserve",
	0,
	"Preserve file times (atime+mtime)."
    },

    {	OPT_SPLIT, 'z', "split",
	0,
	"Enable output file splitting, default split size = 4 GB."
    },

    {	OPT_SPLIT_SIZE, 'Z', "split-size",
	"sz",
	"Enable output file splitting and define split size. The parameter"
	" 'sz' is a floating point number followed by an optional unit factor"
	" (one of 'cb' [=1] or  'kmgtpe' [base=1000] or 'KMGTPE' [base=1024])."
	" The default unit is 'G' (GiB)."
    },

    {	OPT_CHUNK_MODE, 0, "chunk-mode",
	"mode",
	"Defines an operation mode for --max-chunks and --chunk-size. Allowed"
	" values are 'ISO' for ISO images, 'POW2' to force chunk sizes >= 32"
	" KiB and with power of 2 '32K' to force chunk sizes multiple 32 KiB"
	" or 'ANY' to allow any values. The default value is 'POW2'. The case"
	" fo the keyword is ignored."
    },

    {	OPT_CHUNK_SIZE, 0, "chunk-size",
	"sz",
	"Define the minimal chunk size if creating a CISO file. The default is"
	" to calculate the chunk size from the input file size and find a good"
	" value by using a minimal value of 1 MiB for '--chunk-mode AUTO' and"
	" 32 KiB for other mdoes. If --chunk-mode is not 'ANY' then the value"
	" is rounded up to the next power of 2. This calculation also depends"
	" from --max-chunks.\n"
	"The parameter 'sz' is a floating point number followed by an optional"
	" unit factor (one of 'cb' [=1] or  'kmgtpe' [base=1000] or 'KMGTPE'"
	" [base=1024]). The default unit is 'M' (MiB). If the number is"
	" prefixed with a '=' than option --chunk-mode is ignored and the"
	" given value is used without any rounding or changing.\n"
	"If the input file size is not known (e.g. reading from pipe), the"
	" default is 1 MiB."
    },

    {	OPT_MAX_CHUNKS, 0, "max-chunks",
	"n",
	"Define the maximal number of chunks if creating a CISO file. The"
	" default value is 8192 for '--chunk-mode AUTO' and 32760 (maximal"
	" value) for toher modes. If this value is set than the automatic"
	" calculation  of --chunk-size will be modified too."
    },

    {	OPT_OVERWRITE, 'o', "overwrite",
	0,
	"Overwrite already existing files."
    },

    {	OPT_STDOUT, 'c', "stdout",
	0,
	"Write to standard output (stdout) and keep original files unchanged.\n"
	"This is the default, when the program is reading from standard input"
	" (stdin)."
    },

    {	OPT_KEEP, 'k', "keep",
	0,
	"Keep (don't delete) input files during (un-)packing."
    },

    {	OPT_QUIET, 'q', "quiet",
	0,
	"Be quiet and print only error messages."
    },

    {	OPT_VERBOSE, 'v', "verbose",
	0,
	"Be verbose -> print program name."
    },

    {	OPT_CHUNK, 0, "chunk",
	0,
	"In dump mode: Print table with chunk header too."
    },

    {	OPT_LONG, 'l', "long",
	0,
	"Print (un)pack statistics, 1 line for each source. In dump mode:"
	" Print table with chunk header too (same as --chunk)."
    },

    {	OPT_IO, 0, "io",
	"flags",
	"Setup the IO mode for experiments. The standard file IO is based on"
	" open() function. The value '1' defines that WBFS IO is based on"
	" fopen() function. The value '2' defines the same for ISO files and"
	" the value '3' for both, WBFS and ISO."
    },

    {	OPT_TEST, 't', "test",
	0,
	"Run in test mode, modify nothing.\n"
	">>> USE THIS OPTION IF UNSURE! <<<"
    },

    {0,0,0,0,0} // OPT__N_TOTAL == 30

};

//
///////////////////////////////////////////////////////////////////////////////
///////////////            OptionShort & OptionLong             ///////////////
///////////////////////////////////////////////////////////////////////////////

const char OptionShort[] = "VhPUAMXWCs:d:D:pzZ:ockqvlt";

const struct option OptionLong[] =
{
	{ "version",		0, 0, 'V' },
	{ "help",		0, 0, 'h' },
	{ "xhelp",		0, 0, GO_XHELP },
	{ "pack",		0, 0, 'P' },
	{ "unpack",		0, 0, 'U' },
	{ "cat",		0, 0, 'A' },
	{ "cmp",		0, 0, 'M' },
	 { "diff",		0, 0, 'M' },
	{ "dump",		0, 0, 'X' },
	{ "wdf",		0, 0, 'W' },
	{ "ciso",		0, 0, 'C' },
	{ "wbi",		0, 0, GO_WBI },
	{ "suffix",		1, 0, 's' },
	{ "dest",		1, 0, 'd' },
	{ "DEST",		1, 0, 'D' },
	{ "preserve",		0, 0, 'p' },
	{ "split",		0, 0, 'z' },
	{ "split-size",		1, 0, 'Z' },
	 { "splitsize",		1, 0, 'Z' },
	{ "chunk-mode",		1, 0, GO_CHUNK_MODE },
	 { "chunkmode",		1, 0, GO_CHUNK_MODE },
	{ "chunk-size",		1, 0, GO_CHUNK_SIZE },
	 { "chunksize",		1, 0, GO_CHUNK_SIZE },
	{ "max-chunks",		1, 0, GO_MAX_CHUNKS },
	 { "maxchunks",		1, 0, GO_MAX_CHUNKS },
	{ "overwrite",		0, 0, 'o' },
	{ "stdout",		0, 0, 'c' },
	{ "keep",		0, 0, 'k' },
	{ "quiet",		0, 0, 'q' },
	{ "verbose",		0, 0, 'v' },
	{ "chunk",		0, 0, GO_CHUNK },
	{ "long",		0, 0, 'l' },
	{ "io",			1, 0, GO_IO },
	{ "test",		0, 0, 't' },

	{0,0,0,0}
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////            OptionUsed & OptionIndex             ///////////////
///////////////////////////////////////////////////////////////////////////////

u8 OptionUsed[OPT__N_TOTAL+1] = {0};

const u8 OptionIndex[OPT_INDEX_SIZE] = 
{
	/*00*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*10*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*20*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*30*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*40*/	 0,
	/*41*/	OPT_CAT,
	/*42*/	 0,
	/*43*/	OPT_CISO,
	/*44*/	OPT_DEST2,
	/*45*/	 0,0,0,0, 0,0,0,0, 
	/*4d*/	OPT_CMP,
	/*4e*/	 0,0,
	/*50*/	OPT_PACK,
	/*51*/	 0,0,0,0, 
	/*55*/	OPT_UNPACK,
	/*56*/	OPT_VERSION,
	/*57*/	OPT_WDF,
	/*58*/	OPT_DUMP,
	/*59*/	 0,
	/*5a*/	OPT_SPLIT_SIZE,
	/*5b*/	 0,0,0,0, 0,0,0,0, 
	/*63*/	OPT_STDOUT,
	/*64*/	OPT_DEST,
	/*65*/	 0,0,0,
	/*68*/	OPT_HELP,
	/*69*/	 0,0,
	/*6b*/	OPT_KEEP,
	/*6c*/	OPT_LONG,
	/*6d*/	 0,0,
	/*6f*/	OPT_OVERWRITE,
	/*70*/	OPT_PRESERVE,
	/*71*/	OPT_QUIET,
	/*72*/	 0,
	/*73*/	OPT_SUFFIX,
	/*74*/	OPT_TEST,
	/*75*/	 0,
	/*76*/	OPT_VERBOSE,
	/*77*/	 0,0,0,
	/*7a*/	OPT_SPLIT,
	/*7b*/	 0,0,0,0, 0,
	/*80*/	OPT_XHELP,
	/*81*/	OPT_WBI,
	/*82*/	OPT_CHUNK_MODE,
	/*83*/	OPT_CHUNK_SIZE,
	/*84*/	OPT_MAX_CHUNKS,
	/*85*/	OPT_CHUNK,
	/*86*/	OPT_IO,
	/*87*/	 0,0,0,0, 0,0,0,0, 0,
	/*90*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*a0*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                 InfoOption tabs                 ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoOption_t * option_tab_tool[] =
{
	OptionInfo + OPT_VERSION,
	OptionInfo + OPT_HELP,
	OptionInfo + OPT_XHELP,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_PACK,
	OptionInfo + OPT_UNPACK,
	OptionInfo + OPT_CAT,
	OptionInfo + OPT_CMP,
	OptionInfo + OPT_DUMP,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_WDF,
	OptionInfo + OPT_CISO,
	OptionInfo + OPT_WBI,
	OptionInfo + OPT_SUFFIX,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_DEST,
	OptionInfo + OPT_DEST2,
	OptionInfo + OPT_PRESERVE,
	OptionInfo + OPT_SPLIT,
	OptionInfo + OPT_SPLIT_SIZE,
	OptionInfo + OPT_CHUNK_MODE,
	OptionInfo + OPT_CHUNK_SIZE,
	OptionInfo + OPT_MAX_CHUNKS,
	OptionInfo + OPT_OVERWRITE,
	OptionInfo + OPT_STDOUT,
	OptionInfo + OPT_KEEP,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	OptionInfo + OPT_VERBOSE,
	OptionInfo + OPT_CHUNK,
	OptionInfo + OPT_LONG,
	OptionInfo + OPT_IO,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	0
};


//
///////////////////////////////////////////////////////////////////////////////
///////////////                   InfoCommand                   ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoCommand_t CommandInfo[CMD__N+1] =
{
    {	0,
	false,
	false,
	"wdf",
	0,
	"wdf [option]... files...",
	"wdf is a support tool for WDF and CISO archives. It convert (pack and"
	" unpack) WDF and CISO archives. Dependent from file name and from"
	" options it works like 'gzip', 'gunzip' or 'zcat' (see options for"
	" details). It can also compare files and dump the data structure of"
	" those archives for analysis.",
	29,
	option_tab_tool
    },

    {0,0,0,0,0,0,0,0}
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                     InfoUI                      ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoUI_t InfoUI =
{
	"wdf",
	0, // n_cmd
	0, // cmd_tab
	CommandInfo,
	0, // n_opt_specific
	OPT__N_TOTAL,
	OptionInfo,
	OptionUsed,
	OptionIndex,
	OptionShort,
	OptionLong
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                       END                       ///////////////
///////////////////////////////////////////////////////////////////////////////

