
/***************************************************************************
 *                                                                         *
 *   This file is part of the WIT project. It is automatically generated   *
 *   by the project helper 'gen-ui'.                                       *
 *                                                                         *
 *                      ==> DO NOT EDIT THIS FILE <==                      *
 *                                                                         *
 *   Visit http://wit.wiimm.de/ for project details and sources.           *
 *   Copyright (c) 2009-2010 by Dirk Clemens <wiimm@wiimm.de>              *
 *                                                                         *
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   See file gpl-2.0.txt or http://www.gnu.org/licenses/gpl-2.0.txt       *
 *                                                                         *
 ***************************************************************************/

#include <getopt.h>
#include "ui-wwt.h"

//
///////////////////////////////////////////////////////////////////////////////
///////////////                  OptionInfo[]                   ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoOption_t OptionInfo[OPT__N_TOTAL+1] =
{
    {0,0,0,0,0}, // OPT_NONE,

    //----- command specific options -----

    {	OPT_AUTO, 'a', "auto",
	0,
	"Search for WBFS partitions using '/proc/partitions' or searching hard"
	" disks in '/dev/'."
    },

    {	OPT_ALL, 'A', "all",
	0,
	"Use all WBFS partitions found."
    },

    {	OPT_PART, 'p', "part",
	"part",
	"Define a primary WBFS partition. Multiple usage possible."
    },

    {	OPT_RECURSE, 'r', "recurse",
	"path",
	"ISO file or base of a directory tree with ISO files."
    },

    {	OPT_RDEPTH, 0, "rdepth",
	"depth",
	"Set the maximum recurse depth for option --recurse (default=10)."
    },

    {	OPT_PSEL, 0, "psel",
	"list",
	"This option set the scrubbing mode and defines, which disc partitions"
	" are handled. The parameter is a comma separated list of keywords."
	" The keywords are divided in three functional groups:\n"
	"The first group selects partition types. The names DATA, UDDATE,"
	" CHANNEL, ID and the numbers between 0 and 50 for partition type are"
	" allowed. 'ID' is a placeholder for all ID types like the VC channels"
	" of SSBB. The prefix '-' means: disable this partition type. The"
	" special keyword 'NONE' diables all partition types.\n"
	"The second group selects partition tables. The names PTAB0..PTAB3"
	" (and T0..T3) are allowed. The prefix '-' means: Disable all"
	" partitions of that partition table.\n"
	"The third group are additional flags: 'WHOLE' means that the whole"
	" partition data is used. 'RAW' means that the whole disc is selected.\n"
	"The special keyword 'ALL' resets all settings to the default."
    },

    {	OPT_RAW, 0, "raw",
	0,
	"Abbreviation of '--psel RAW'."
    },

    {	OPT_INCLUDE, 'n', "include",
	"id",
	"Include only discs with given ID4 or ID6 from operation. If the"
	" parameter begins with a '@' the given file is read and each line is"
	" scanned for IDs."
    },

    {	OPT_INCLUDE_PATH, 'N', "include-path",
	"file_or_dir",
	"ISO file or base of directory tree -> scan their ID6."
    },

    {	OPT_EXCLUDE, 'x', "exclude",
	"id",
	"Exclude discs with given ID4 or ID6 from operation. If the parameter"
	" begins with a '@' the given file is read and each line is scanned"
	" for IDs."
    },

    {	OPT_EXCLUDE_PATH, 'X', "exclude-path",
	"file_or_dir",
	"ISO file or base of directory tree -> scan their ID6."
    },

    {	OPT_IGNORE, 'i', "ignore",
	0,
	"Ignore non existing files/discs without warning. If set twice then"
	" all non Wii ISO images are ignored too."
    },

    {	OPT_IGNORE_FST, 0, "ignore-fst",
	0,
	"Disable composing and ignore FST directories as input."
    },

    {	OPT_ID, 0, "id",
	"id",
	"This patching option changes the ID of the disc to the given"
	" parameter. 1 to 6 characters are expected. Only defined characters"
	" not equal '.' are modified. The disc header, boot.bin, ticket.bin"
	" and tmd.bin are  objects to modify. The option --modify selects the"
	" objects."
    },

    {	OPT_NAME, 0, "name",
	"name",
	"This patching option changes the name (disc title) of the disc to the"
	" given parameter. Up to 63 characters are expected. The disc header"
	" and boot.bin are objects to modify. The option --modify selects the"
	" objects."
    },

    {	OPT_MODIFY, 0, "modify",
	"list",
	" This patching option expects a comma separated list of the following"
	" keywords (case ignored) as parameter: NONE, DISC, BOOT, TICKET, TMD,"
	" WBFS, ALL and AUTO (default).\n"
	"All keywords can be prefixed by '+' to enable that option, by a '-'"
	" to disable it or by a '=' to enable that option and disable all"
	" others."
    },

    {	OPT_REGION, 0, "region",
	"region",
	"This patching option defines the region of the disc.  The region is"
	" one of JAPAN, USA, EUROPE, KOREA, FILE or AUTO (default). The case"
	" of the keywords is ignored. Unsigned numbers are also accepted."
    },

    {	OPT_IOS, 0, "ios",
	"ios",
	"This patching option defines the system version (IOS to load) within"
	" TMD. The format is 'HIGH:LOW' or 'HIGH-LOW' or 'LOW'. If only LOW is"
	" set than HIGH is assumed as 1 (standard IOS)."
    },

    {	OPT_RM_FILES, 0, "rm-files",
	"rules",
	"Define a filter rules to removes real files and directories from the"
	" FST."
    },

    {	OPT_ZERO_FILES, 0, "zero-files",
	"rules",
	"Define a filter rules to zero real files from the FST."
    },

    {	OPT_IGNORE_FILES, 0, "ignore-files",
	"rules",
	"Define a filter rules to ignore system and real files from the FST."
    },

    {	OPT_ENC, 0, "enc",
	"encoding",
	"Define the encoding mode. The mode is one of NONE, HASHONLY, DECRYPT,"
	" ENCRYPT, SIGN or AUTO. The case of the keywords is ignored. The"
	" default mode is 'AUTO'."
    },

    {	OPT_DEST, 'd', "dest",
	"path",
	"Define a destination path (directory/file). The destination path is"
	" scanned for escape sequences (see option --esc) to allow generic"
	" pathes."
    },

    {	OPT_DEST2, 'D', "DEST",
	"path",
	"Like --dest, but create the directory path automatically."
    },

    {	OPT_SPLIT, 'z', "split",
	0,
	"Enable output file splitting, default split size = 4 GB."
    },

    {	OPT_SPLIT_SIZE, 'Z', "split-size",
	"sz",
	"Enable output file splitting and define split size. The parameter"
	" 'sz' is a floating point number followed by an optional unit factor"
	" (one of 'cb' [=1] or  'kmgtpe' [base=1000] or 'KMGTPE' [base=1024])."
	" The default unit is 'G' (GiB)."
    },

    {	OPT_TRUNC, 0, "trunc",
	0,
	"Truncate PLAIN ISO images to the needed size while creating."
    },

    {	OPT_FAST, 'F', "fast",
	0,
	"Enables fast writing (disables searching for blocks with zeroed"
	" data)."
    },

    {	OPT_CHUNK_MODE, 0, "chunk-mode",
	"mode",
	"Defines an operation mode for --chunk-size and --max-chunks. Allowed"
	" keywords are 'ANY' to allow any values,, '32K' to force chunk sizes"
	" with a multiple of 32 KiB, 'POW2' to force chunk sizes >=32K and"
	" with a power of 2 or 'ISO' for ISO images (more restrictive as"
	" 'POW2', best for USB loaders). The case of the keyword is ignored."
	" The default key is 'ISO'.\n"
	"--chm is a shortcut for --chunk-mode."
    },

    {	OPT_CHUNK_SIZE, 0, "chunk-size",
	"sz",
	"Define the minimal chunk size if creating a CISO file. The default is"
	" to calculate the chunk size from the input file size and find a good"
	" value by using a minimal value of 1 MiB for '--chunk-mode ISO' and"
	" 32 KiB for modes 32K and POW2. For the modes ISO and POW2 the value"
	" is rounded up to the next power of 2. This calculation also depends"
	" from option --max-chunks.\n"
	"The parameter 'sz' is a floating point number followed by an optional"
	" unit factor (one of 'cb' [=1] or  'kmgtpe' [base=1000] or 'KMGTPE'"
	" [base=1024]). The default unit is 'M' (MiB). If the number is"
	" prefixed with a '=' then options --chunk-mode and --max-chunks are"
	" ignored and the given value is used without any rounding or"
	" changing.\n"
	"If the input file size is not known (e.g. reading from pipe), its"
	" size is assumed as 12 GiB.\n"
	" --chz is a shortcut for --chunk-size."
    },

    {	OPT_MAX_CHUNKS, 0, "max-chunks",
	"n",
	"Define the maximal number of chunks if creating a CISO file. The"
	" default value is 8192 for '--chunk-mode ISO' and 32760 (maximal"
	" value) for all other modes. If this value is set than the automatic"
	" calculation  of --chunk-size will be modified too.\n"
	" --mch is a shortcut for --max-chunks."
    },

    {	OPT_SIZE, 's', "size",
	"size",
	"Floating point size. Factors: bckKmMgGtT, default=G."
    },

    {	OPT_HSS, 0, "hss",
	"size",
	"Define HD sector size, default=512. Factors: kKmMgGtT"
    },

    {	OPT_WSS, 0, "wss",
	"size",
	"Define WBFS sector size, no default. Factors: kKmMgGtT"
    },

    {	OPT_RECOVER, 0, "recover",
	0,
	"Format a WBFS in recover mode."
    },

    {	OPT_FORCE, 'f', "force",
	0,
	"Force operation."
    },

    {	OPT_NO_CHECK, 0, "no-check",
	0,
	"Disable automatic check of WBFS before modificastions."
    },

    {	OPT_REPAIR, 0, "repair",
	"mode",
	"This option defines how to repair WBFS errors. The parameter is a"
	" comma separated list of the following keywords, case is ignored:"
	" NONE, FBT, INODES, STANDARD, RM-INVALID, RM-OVERLAP, RM-FREE,"
	" RM-EMPTY, RM-ALL, ALL.\n"
	"All keywords can be prefixed by '+' to enable that option, by a '-'"
	" to disable it or by a '=' to enable that option and disable all"
	" others."
    },

    {	OPT_NO_FREE, 0, "no-free",
	0,
	"The discs are only dropped (slot is marked free), but the"
	" correspondent blocks are not freed. You should run CHECK or REPAIR"
	" to repair the WBFS after using this option."
    },

    {	OPT_UPDATE, 'u', "update",
	0,
	"Copy only non existing discs."
    },

    {	OPT_SYNC, 'y', "sync",
	0,
	"Remove and copy discs until the destination WBFS contains exactly the"
	" same discs as all sources together."
    },

    {	OPT_NEWER, 'e', "newer",
	0,
	"If source and dest have valid mtimes: copy if source is newer."
    },

    {	OPT_OVERWRITE, 'o', "overwrite",
	0,
	"Overwrite already existing files."
    },

    {	OPT_REMOVE, 'R', "remove",
	0,
	"Remove source files/discs if operation is successful."
    },

    {	OPT_WDF, 'W', "wdf",
	0,
	"Set ISO output file type to WDF. (default)"
    },

    {	OPT_ISO, 'I', "iso",
	0,
	"Set ISO output file type to PLAIN ISO."
    },

    {	OPT_CISO, 'C', "ciso",
	0,
	"Set ISO output file type to CISO (=WBI)."
    },

    {	OPT_WBFS, 'B', "wbfs",
	0,
	"Set ISO output file type to WBFS container."
    },

    {	OPT_ITIME, 0, "itime",
	0,
	"Select 'itime' (insertion time) for printing. --itime is an"
	" abbreviation of '--time i'."
    },

    {	OPT_MTIME, 0, "mtime",
	0,
	"Select 'mtime' (last modification time) for printing. --mtime is an"
	" abbreviation of '--time m'."
    },

    {	OPT_CTIME, 0, "ctime",
	0,
	"Select 'ctime' (last status change time) for printing. --ctime is an"
	" abbreviation of '--time c'."
    },

    {	OPT_ATIME, 0, "atime",
	0,
	"Select 'atime' (last access time) for printing. --atime is an"
	" abbreviation of '--time a'."
    },

    {	OPT_TIME, 0, "time",
	"list",
	"Set time printing and sorting mode The parameter is a comma separated"
	" list of the following keywords, case is ignored: RESET, OFF, ON,"
	" SINGLE, MULTI, NONE, ALL, I, M, C, A, DATE, TIME, SEC, IDATE, MDATE,"
	" CDATE, ADATE, ITIME, MTIME, CTIME, ATIME, ISEC, MSEC, CSEC, ASEC."
    },

    {	OPT_SET_TIME, 0, "set-time",
	"time",
	"Use given time instead of current time."
    },

    {	OPT_LONG, 'l', "long",
	0,
	"Print in long format. Multiple usage possible."
    },

    {	OPT_INODE, 0, "inode",
	0,
	"Print information for all inodes (invalid discs too)."
    },

    {	OPT_MIXED, 'M', "mixed",
	0,
	"Print disc infos of all WBFS in one combined table."
    },

    {	OPT_UNIQUE, 'U', "unique",
	0,
	"Eliminate multiple entries with same values."
    },

    {	OPT_NO_HEADER, 'H', "no-header",
	0,
	"Suppress printing of header and footer."
    },

    {	OPT_SECTIONS, 0, "sections",
	0,
	"Print in machine readable sections and parameter lines."
    },

    {	OPT_SORT, 'S', "sort",
	"list",
	"Define the sort mode for listings. The parameter is a comma separated"
	" list of the following keywords: NONE, NAME, TITLE, FILE, SIZE,"
	" OFFSET, REGION, WBFS, NPART, ITIME, MTIME, CTIME, ATIME, TIME ="
	" DATE, DEFAULT, ASCENDING, DESCENDING = REVERSE."
    },

    {	OPT_LIMIT, 0, "limit",
	"num",
	"Limit the output to NUM messages."
    },

    {0,0,0,0,0}, // OPT__N_SPECIFIC == 63

    //----- global options -----

    {	OPT_VERSION, 'V', "version",
	0,
	"Stop parsing the command line, print a version info and exit."
    },

    {	OPT_HELP, 'h', "help",
	0,
	"Stop parsing the command line, print a help message and exit."
    },

    {	OPT_XHELP, 0, "xhelp",
	0,
	"Stop parsing the command line and print a help message with all"
	" commands included. Exit after printing."
    },

    {	OPT_WIDTH, 0, "width",
	"width",
	"Define the width (number of columns) for help and some other"
	" messages. This option disables the automatic detection of the"
	" terminal width."
    },

    {	OPT_QUIET, 'q', "quiet",
	0,
	"Be quiet and print only error messages."
    },

    {	OPT_VERBOSE, 'v', "verbose",
	0,
	"Be verbose and print more progress information. Multiple usage is"
	" possible: Progress counter is enabled if set at least two times."
	" Extended logging is enabled if set at least four times. The impact"
	" of the other verbose levels are command dependent."
    },

    {	OPT_PROGRESS, 'P', "progress",
	0,
	"Print progress counter independent of verbose level."
    },

    {	OPT_LOGGING, 'L', "logging",
	0,
	"Special logging for patching and composing Wii discs. If set at least"
	" once the disc layout is printed. If set at least twice the partition"
	" layout is printed too."
    },

    {	OPT_ESC, 'E', "esc",
	"char",
	"Define an alternative escape character for destination files. The"
	" default is '%'. For Windows (CYGWIN) it is a good choice to set"
	" '-E$'."
    },

    {	OPT_IO, 0, "io",
	"flags",
	"Setup the IO mode for experiments. The standard file IO is based on"
	" open() function. The value '1' defines that WBFS IO is based on"
	" fopen() function. The value '2' defines the same for ISO files and"
	" the value '3' for both, WBFS and ISO."
    },

    {	OPT_TITLES, 'T', "titles",
	"file",
	"Read file for disc titles. -T0 disables titles lookup."
    },

    {	OPT_UTF_8, 0, "utf-8",
	0,
	"Enables UTF-8 support (default)."
    },

    {	OPT_NO_UTF_8, 0, "no-utf-8",
	0,
	"Disables UTF-8 support (CYGWIN default)."
    },

    {	OPT_LANG, 0, "lang",
	"lang",
	"Define the language for titles."
    },

    {	OPT_TEST, 't', "test",
	0,
	"Run in test mode, modify nothing.\n"
	">>> USE THIS OPTION IF UNSURE! <<<"
    },

    {	OPT_HOOK, 0, "hook",
	0,
	"Force relocation hook while reading iso images."
    },

    {0,0,0,0,0} // OPT__N_TOTAL == 79

};

//
///////////////////////////////////////////////////////////////////////////////
///////////////             alternate option infos              ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoOption_t option_grp_MOD_WBFS_FORCE =
    {	OPT_FORCE, 'f', "force",
	0,
	"If the automatic check finds problematic errors, then the report is"
	" printed but the operation is *not* canceled."
    };

const InfoOption_t option_grp_MOD_WBFS_NO_CHECK =
    {	OPT_NO_CHECK, 0, "no-check",
	0,
	"Disable automatic check of WBFS before modifications."
    };

const InfoOption_t option_grp_VERBOSE_VERBOSE =
    {	OPT_VERBOSE, 'v', "verbose",
	0,
	"Show a runtime summary for each job. If set twice enable progress"
	" information. If set three times the progress information is more"
	" detailed."
    };

const InfoOption_t option_cmd_ERROR_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"Print extended message instead of error name."
    };

const InfoOption_t option_cmd_FIND_QUIET =
    {	OPT_QUIET, 'q', "quiet",
	0,
	"Be absoulte quiet and report the find status as exit code only."
    };

const InfoOption_t option_cmd_FIND_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"Without --long only partition names of WBFS partitions are printed."
	" If option --long is set then additional infos are printed for each"
	" partition, WBFS or not. If option --long is set at least twice the"
	" real path is printed."
    };

const InfoOption_t option_cmd_SPACE_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	" If option --long is set the real path is printed."
    };

const InfoOption_t option_cmd_ANALYZE_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"If option --long is set then calculated values are printed too if"
	" other values are available. If option --long is set twice calculated"
	" values are always printed."
    };

const InfoOption_t option_cmd_DUMP_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"If set then print a status for each valid disc within WBFS. If set"
	" twice print a memory map for each shown disc too. If set three times"
	" print an additional memory map for the whole WBFS. If set four times"
	" activate --inode too."
    };

const InfoOption_t option_cmd_ID6_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"Prefix each printed ID6 with the WBFS filename."
    };

const InfoOption_t option_cmd_LIST_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"If set the size in MiB and the region is printed too. If set twice at"
	" least on time columns is added."
    };

const InfoOption_t option_cmd_FORMAT_VERBOSE =
    {	OPT_VERBOSE, 'v', "verbose",
	0,
	"Be verbose and explain the actions."
    };

const InfoOption_t option_cmd_FORMAT_INODE =
    {	OPT_INODE, 0, "inode",
	0,
	"Force creating inode infos with predefined timestamps. The timestamps"
	" reduce effect of sparce files. This option is set for devices"
	" automatically."
    };

const InfoOption_t option_cmd_FORMAT_TEST =
    {	OPT_TEST, 't', "test",
	0,
	"Force test mode and ignore --force."
    };

const InfoOption_t option_cmd_FORMAT_FORCE =
    {	OPT_FORCE, 'f', "force",
	0,
	"This option is needed for leaving test mode and for formatting!"
    };

const InfoOption_t option_grp_CHECK_VERBOSE =
    {	OPT_VERBOSE, 'v', "verbose",
	0,
	"Be verbose. If set once then more detaiuls are printed. If set twice"
	" a info dump of all coruppted discs is included. If set three times a"
	" info dump of all discs is included if a error is found. If set four"
	" times a full memory mal is included."
    };

const InfoOption_t option_grp_CHECK_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"Option --long does the same as option --verbose. If set at last once"
	" it overwrites the --verbose level."
    };

const InfoOption_t option_cmd_CHECK_REPAIR =
    {	OPT_REPAIR, 0, "repair",
	"mode",
	"This option defines how to repair WBFS errors. The parameter is a"
	" comma separated list of the following keywords, case is ignored:"
	" NONE, FBT, INODES, STANDARD, RM-INVALID, RM-OVERLAP, RM-FREE,"
	" RM-EMPTY, RM-ALL, ALL.\n"
	"All keywords can be prefixed by '+' to enable that option, by a '-'"
	" to disable it or by a '=' to enable that option and disable all"
	" others. The default is 'NONE'."
    };

const InfoOption_t option_cmd_REPAIR_REPAIR =
    {	OPT_REPAIR, 0, "repair",
	"mode",
	"This option defines how to repair WBFS errors. The parameter is a"
	" comma separated list of the following keywords, case is ignored:"
	" NONE, FBT, INODES, STANDARD, RM-INVALID, RM-OVERLAP, RM-FREE,"
	" RM-EMPTY, RM-ALL, ALL.\n"
	"All keywords can be prefixed by '+' to enable that option, by a '-'"
	" to disable it or by a '=' to enable that option and disable all"
	" others. The default is 'STANDARD' (FBT,INODES)."
    };

const InfoOption_t option_cmd_EDIT_TEST =
    {	OPT_TEST, 't', "test",
	0,
	"Force test mode and ignore --force."
    };

const InfoOption_t option_cmd_EDIT_FORCE =
    {	OPT_FORCE, 'f', "force",
	0,
	"This option is needed for leaving test mode and for formatting!"
    };

const InfoOption_t option_cmd_PHANTOM_VERBOSE =
    {	OPT_VERBOSE, 'v', "verbose",
	0,
	"Print a status line for each added disc."
    };

const InfoOption_t option_cmd_SYNC_TRUNC =
    {	OPT_TRUNC, 0, "trunc",
	0,
	"Truncate WBFS until operation finished."
    };

const InfoOption_t option_cmd_ADD_OVERWRITE =
    {	OPT_OVERWRITE, 'o', "overwrite",
	0,
	"Overwrite already existing discs."
    };

const InfoOption_t option_cmd_EXTRACT_UNIQUE =
    {	OPT_UNIQUE, 'U', "unique",
	0,
	"Eliminate multiple ID6 from the source list."
    };

const InfoOption_t option_cmd_EXTRACT_IGNORE =
    {	OPT_IGNORE, 'i', "ignore",
	0,
	"Ignore non existing discs without any warning."
    };

const InfoOption_t option_cmd_REMOVE_UNIQUE =
    {	OPT_UNIQUE, 'U', "unique",
	0,
	"Eliminate multiple ID6 from the source list."
    };

const InfoOption_t option_cmd_REMOVE_IGNORE =
    {	OPT_IGNORE, 'i', "ignore",
	0,
	"Ignore non existing discs without any warning."
    };

const InfoOption_t option_cmd_RENAME_IGNORE =
    {	OPT_IGNORE, 'i', "ignore",
	0,
	"Ignore non existing discs without any warning."
    };

const InfoOption_t option_cmd_RENAME_ISO =
    {	OPT_ISO, 'I', "iso",
	0,
	"Modify ID and title of the ISO image. If neither --iso nor --wbfs is"
	" set, then both are assumed as active."
    };

const InfoOption_t option_cmd_RENAME_WBFS =
    {	OPT_WBFS, 'B', "wbfs",
	0,
	"Modify ID and title of the inode in the WBFS management area. If"
	" neither --iso nor --wbfs is set, then both are assumed as active."
    };

const InfoOption_t option_cmd_TOUCH_UNIQUE =
    {	OPT_UNIQUE, 'U', "unique",
	0,
	"Eliminate multiple ID6 from the source list."
    };

const InfoOption_t option_cmd_TOUCH_IGNORE =
    {	OPT_IGNORE, 'i', "ignore",
	0,
	"Ignore non existing discs without any warning."
    };

const InfoOption_t option_cmd_TOUCH_ITIME =
    {	OPT_ITIME, 0, "itime",
	0,
	"Touch the 'itime' (insertion time)."
    };

const InfoOption_t option_cmd_TOUCH_MTIME =
    {	OPT_MTIME, 0, "mtime",
	0,
	"Touch the 'mtime' (last modification time)."
    };

const InfoOption_t option_cmd_TOUCH_CTIME =
    {	OPT_CTIME, 0, "ctime",
	0,
	"Touch the 'ctime' (last status change time)."
    };

const InfoOption_t option_cmd_TOUCH_ATIME =
    {	OPT_ATIME, 0, "atime",
	0,
	"Touch the 'atime' (last access time)."
    };

const InfoOption_t option_cmd_VERIFY_LIMIT =
    {	OPT_LIMIT, 0, "limit",
	"num",
	"Maximal printed errors of each partition. A zero means unlimitted."
	" The default is 10."
    };

const InfoOption_t option_cmd_VERIFY_UNIQUE =
    {	OPT_UNIQUE, 'U', "unique",
	0,
	"Eliminate multiple ID6 from the source list."
    };

const InfoOption_t option_cmd_VERIFY_IGNORE =
    {	OPT_IGNORE, 'i', "ignore",
	0,
	"Ignore non existing discs without any warning."
    };

const InfoOption_t option_cmd_VERIFY_REMOVE =
    {	OPT_REMOVE, 'R', "remove",
	0,
	"Remove bad discs from WBFS."
    };

const InfoOption_t option_cmd_VERIFY_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"On error print an additional line to localize the exact position"
	" where the error is found. If set twice a hexdump of the hash values"
	" is printed too."
    };

const InfoOption_t option_cmd_FILETYPE_LONG =
    {	OPT_LONG, 'l', "long",
	0,
	"If set then ID6 and split file count are printed too. If set twice"
	" the region is printed too."
    };


//
///////////////////////////////////////////////////////////////////////////////
///////////////                  CommandTab[]                   ///////////////
///////////////////////////////////////////////////////////////////////////////

const CommandTab_t CommandTab[] =
{
    { CMD_VERSION,	"VERSION",	0,		OB_CMD_VERSION },
    { CMD_HELP,		"HELP",		"H",		OB_CMD_HELP },
    { CMD_HELP,		"?",		0,		OB_CMD_HELP },
    { CMD_TEST,		"TEST",		0,		OB_CMD_TEST },
    { CMD_ERROR,	"ERROR",	"ERR",		OB_CMD_ERROR },
    { CMD_EXCLUDE,	"EXCLUDE",	0,		OB_CMD_EXCLUDE },
    { CMD_TITLES,	"TITLES",	0,		OB_CMD_TITLES },
    { CMD_FIND,		"FIND",		"F",		OB_CMD_FIND },
    { CMD_SPACE,	"SPACE",	"DF",		OB_CMD_SPACE },
    { CMD_ANALYZE,	"ANALYZE",	"ANA",		OB_CMD_ANALYZE },
    { CMD_ANALYZE,	"ANALYSE",	0,		OB_CMD_ANALYZE },
    { CMD_DUMP,		"DUMP",		"D",		OB_CMD_DUMP },
    { CMD_ID6,		"ID6",		"ID",		OB_CMD_ID6 },
    { CMD_LIST,		"LIST",		"LS",		OB_CMD_LIST },
    { CMD_LIST_L,	"LIST-L",	"LL",		OB_CMD_LIST_L },
    { CMD_LIST_L,	"LISTL",	0,		OB_CMD_LIST_L },
    { CMD_LIST_LL,	"LIST-LL",	"LLL",		OB_CMD_LIST_LL },
    { CMD_LIST_LL,	"LISTLL",	0,		OB_CMD_LIST_LL },
    { CMD_LIST_A,	"LIST-A",	"LA",		OB_CMD_LIST_A },
    { CMD_LIST_A,	"LISTA",	0,		OB_CMD_LIST_A },
    { CMD_LIST_M,	"LIST-M",	"LM",		OB_CMD_LIST_M },
    { CMD_LIST_M,	"LISTM",	0,		OB_CMD_LIST_M },
    { CMD_LIST_U,	"LIST-U",	"LU",		OB_CMD_LIST_U },
    { CMD_LIST_U,	"LISTU",	0,		OB_CMD_LIST_U },
    { CMD_FORMAT,	"FORMAT",	"INIT",		OB_CMD_FORMAT },
    { CMD_RECOVER,	"RECOVER",	0,		OB_CMD_RECOVER },
    { CMD_CHECK,	"CHECK",	"FSCK",		OB_CMD_CHECK },
    { CMD_REPAIR,	"REPAIR",	0,		OB_CMD_REPAIR },
    { CMD_EDIT,		"EDIT",		0,		OB_CMD_EDIT },
    { CMD_PHANTOM,	"PHANTOM",	0,		OB_CMD_PHANTOM },
    { CMD_TRUNCATE,	"TRUNCATE",	"TR",		OB_CMD_TRUNCATE },
    { CMD_ADD,		"ADD",		"A",		OB_CMD_ADD },
    { CMD_UPDATE,	"UPDATE",	"U",		OB_CMD_UPDATE },
    { CMD_SYNC,		"SYNC",		0,		OB_CMD_SYNC },
    { CMD_EXTRACT,	"EXTRACT",	"X",		OB_CMD_EXTRACT },
    { CMD_REMOVE,	"REMOVE",	"RM",		OB_CMD_REMOVE },
    { CMD_RENAME,	"RENAME",	"REN",		OB_CMD_RENAME },
    { CMD_SETTITLE,	"SETTITLE",	"ST",		OB_CMD_SETTITLE },
    { CMD_TOUCH,	"TOUCH",	0,		OB_CMD_TOUCH },
    { CMD_VERIFY,	"VERIFY",	"V",		OB_CMD_VERIFY },
    { CMD_FILETYPE,	"FILETYPE",	"FT",		OB_CMD_FILETYPE },

    { CMD__N,0,0,0 }
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////            OptionShort & OptionLong             ///////////////
///////////////////////////////////////////////////////////////////////////////

const char OptionShort[] = "VhqvPLE:T:taAp:r:n:N:x:X:id:D:zZ:Fs:fuyeoRWICBlMUHS:";

const struct option OptionLong[] =
{
	{ "version",		0, 0, 'V' },
	{ "help",		0, 0, 'h' },
	{ "xhelp",		0, 0, GO_XHELP },
	{ "width",		1, 0, GO_WIDTH },
	{ "quiet",		0, 0, 'q' },
	{ "verbose",		0, 0, 'v' },
	{ "progress",		0, 0, 'P' },
	{ "logging",		0, 0, 'L' },
	{ "esc",		1, 0, 'E' },
	{ "io",			1, 0, GO_IO },
	{ "titles",		1, 0, 'T' },
	{ "utf-8",		0, 0, GO_UTF_8 },
	 { "utf8",		0, 0, GO_UTF_8 },
	{ "no-utf-8",		0, 0, GO_NO_UTF_8 },
	 { "no-utf8",		0, 0, GO_NO_UTF_8 },
	 { "noutf8",		0, 0, GO_NO_UTF_8 },
	{ "lang",		1, 0, GO_LANG },
	{ "test",		0, 0, 't' },
	{ "auto",		0, 0, 'a' },
	{ "all",		0, 0, 'A' },
	{ "part",		1, 0, 'p' },
	{ "recurse",		1, 0, 'r' },
	{ "rdepth",		1, 0, GO_RDEPTH },
	{ "psel",		1, 0, GO_PSEL },
	{ "raw",		0, 0, GO_RAW },
	{ "include",		1, 0, 'n' },
	{ "include-path",	1, 0, 'N' },
	 { "includepath",	1, 0, 'N' },
	{ "exclude",		1, 0, 'x' },
	{ "exclude-path",	1, 0, 'X' },
	 { "excludepath",	1, 0, 'X' },
	{ "ignore",		0, 0, 'i' },
	{ "ignore-fst",		0, 0, GO_IGNORE_FST },
	 { "ignorefst",		0, 0, GO_IGNORE_FST },
	{ "hook",		0, 0, GO_HOOK },
	{ "id",			1, 0, GO_ID },
	{ "name",		1, 0, GO_NAME },
	{ "modify",		1, 0, GO_MODIFY },
	{ "region",		1, 0, GO_REGION },
	{ "ios",		1, 0, GO_IOS },
	{ "rm-files",		1, 0, GO_RM_FILES },
	{ "zero-files",		1, 0, GO_ZERO_FILES },
	{ "ignore-files",	1, 0, GO_IGNORE_FILES },
	{ "enc",		1, 0, GO_ENC },
	{ "dest",		1, 0, 'd' },
	{ "DEST",		1, 0, 'D' },
	{ "split",		0, 0, 'z' },
	{ "split-size",		1, 0, 'Z' },
	 { "splitsize",		1, 0, 'Z' },
	{ "trunc",		0, 0, GO_TRUNC },
	{ "fast",		0, 0, 'F' },
	{ "chunk-mode",		1, 0, GO_CHUNK_MODE },
	 { "chunkmode",		1, 0, GO_CHUNK_MODE },
	 { "chm",		1, 0, GO_CHUNK_MODE },
	{ "chunk-size",		1, 0, GO_CHUNK_SIZE },
	 { "chunksize",		1, 0, GO_CHUNK_SIZE },
	 { "chz",		1, 0, GO_CHUNK_SIZE },
	{ "max-chunks",		1, 0, GO_MAX_CHUNKS },
	 { "maxchunks",		1, 0, GO_MAX_CHUNKS },
	 { "mch",		1, 0, GO_MAX_CHUNKS },
	{ "size",		1, 0, 's' },
	{ "hss",		1, 0, GO_HSS },
	 { "sector-size",	1, 0, GO_HSS },
	 { "sectorsize",	1, 0, GO_HSS },
	{ "wss",		1, 0, GO_WSS },
	{ "recover",		0, 0, GO_RECOVER },
	{ "force",		0, 0, 'f' },
	{ "no-check",		0, 0, GO_NO_CHECK },
	 { "nocheck",		0, 0, GO_NO_CHECK },
	{ "repair",		1, 0, GO_REPAIR },
	{ "no-free",		0, 0, GO_NO_FREE },
	 { "nofree",		0, 0, GO_NO_FREE },
	{ "update",		0, 0, 'u' },
	{ "sync",		0, 0, 'y' },
	{ "newer",		0, 0, 'e' },
	 { "new",		0, 0, 'e' },
	{ "overwrite",		0, 0, 'o' },
	{ "remove",		0, 0, 'R' },
	{ "wdf",		0, 0, 'W' },
	{ "iso",		0, 0, 'I' },
	{ "ciso",		0, 0, 'C' },
	{ "wbfs",		0, 0, 'B' },
	{ "itime",		0, 0, GO_ITIME },
	{ "mtime",		0, 0, GO_MTIME },
	{ "ctime",		0, 0, GO_CTIME },
	{ "atime",		0, 0, GO_ATIME },
	{ "time",		1, 0, GO_TIME },
	{ "set-time",		1, 0, GO_SET_TIME },
	 { "settime",		1, 0, GO_SET_TIME },
	{ "long",		0, 0, 'l' },
	{ "inode",		0, 0, GO_INODE },
	{ "mixed",		0, 0, 'M' },
	{ "unique",		0, 0, 'U' },
	{ "no-header",		0, 0, 'H' },
	 { "noheader",		0, 0, 'H' },
	{ "sections",		0, 0, GO_SECTIONS },
	{ "sort",		1, 0, 'S' },
	{ "limit",		1, 0, GO_LIMIT },

	{0,0,0,0}
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////            OptionUsed & OptionIndex             ///////////////
///////////////////////////////////////////////////////////////////////////////

u8 OptionUsed[OPT__N_TOTAL+1] = {0};

const u8 OptionIndex[OPT_INDEX_SIZE] = 
{
	/*00*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*10*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*20*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*30*/	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/*40*/	 0,
	/*41*/	OPT_ALL,
	/*42*/	OPT_WBFS,
	/*43*/	OPT_CISO,
	/*44*/	OPT_DEST2,
	/*45*/	OPT_ESC,
	/*46*/	OPT_FAST,
	/*47*/	 0,
	/*48*/	OPT_NO_HEADER,
	/*49*/	OPT_ISO,
	/*4a*/	 0,0,
	/*4c*/	OPT_LOGGING,
	/*4d*/	OPT_MIXED,
	/*4e*/	OPT_INCLUDE_PATH,
	/*4f*/	 0,
	/*50*/	OPT_PROGRESS,
	/*51*/	 0,
	/*52*/	OPT_REMOVE,
	/*53*/	OPT_SORT,
	/*54*/	OPT_TITLES,
	/*55*/	OPT_UNIQUE,
	/*56*/	OPT_VERSION,
	/*57*/	OPT_WDF,
	/*58*/	OPT_EXCLUDE_PATH,
	/*59*/	 0,
	/*5a*/	OPT_SPLIT_SIZE,
	/*5b*/	 0,0,0,0, 0,0,
	/*61*/	OPT_AUTO,
	/*62*/	 0,0,
	/*64*/	OPT_DEST,
	/*65*/	OPT_NEWER,
	/*66*/	OPT_FORCE,
	/*67*/	 0,
	/*68*/	OPT_HELP,
	/*69*/	OPT_IGNORE,
	/*6a*/	 0,0,
	/*6c*/	OPT_LONG,
	/*6d*/	 0,
	/*6e*/	OPT_INCLUDE,
	/*6f*/	OPT_OVERWRITE,
	/*70*/	OPT_PART,
	/*71*/	OPT_QUIET,
	/*72*/	OPT_RECURSE,
	/*73*/	OPT_SIZE,
	/*74*/	OPT_TEST,
	/*75*/	OPT_UPDATE,
	/*76*/	OPT_VERBOSE,
	/*77*/	 0,
	/*78*/	OPT_EXCLUDE,
	/*79*/	OPT_SYNC,
	/*7a*/	OPT_SPLIT,
	/*7b*/	 0,0,0,0, 0,
	/*80*/	OPT_XHELP,
	/*81*/	OPT_WIDTH,
	/*82*/	OPT_IO,
	/*83*/	OPT_UTF_8,
	/*84*/	OPT_NO_UTF_8,
	/*85*/	OPT_LANG,
	/*86*/	OPT_RDEPTH,
	/*87*/	OPT_PSEL,
	/*88*/	OPT_RAW,
	/*89*/	OPT_IGNORE_FST,
	/*8a*/	OPT_HOOK,
	/*8b*/	OPT_ID,
	/*8c*/	OPT_NAME,
	/*8d*/	OPT_MODIFY,
	/*8e*/	OPT_REGION,
	/*8f*/	OPT_IOS,
	/*90*/	OPT_RM_FILES,
	/*91*/	OPT_ZERO_FILES,
	/*92*/	OPT_IGNORE_FILES,
	/*93*/	OPT_ENC,
	/*94*/	OPT_TRUNC,
	/*95*/	OPT_CHUNK_MODE,
	/*96*/	OPT_CHUNK_SIZE,
	/*97*/	OPT_MAX_CHUNKS,
	/*98*/	OPT_HSS,
	/*99*/	OPT_WSS,
	/*9a*/	OPT_RECOVER,
	/*9b*/	OPT_NO_CHECK,
	/*9c*/	OPT_REPAIR,
	/*9d*/	OPT_NO_FREE,
	/*9e*/	OPT_ITIME,
	/*9f*/	OPT_MTIME,
	/*a0*/	OPT_CTIME,
	/*a1*/	OPT_ATIME,
	/*a2*/	OPT_TIME,
	/*a3*/	OPT_SET_TIME,
	/*a4*/	OPT_INODE,
	/*a5*/	OPT_SECTIONS,
	/*a6*/	OPT_LIMIT,
	/*a7*/	 0,0,0,0, 0,0,0,0, 0,
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                 InfoOption tabs                 ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoOption_t * option_tab_tool[] =
{
	OptionInfo + OPT_VERSION,
	OptionInfo + OPT_HELP,
	OptionInfo + OPT_XHELP,
	OptionInfo + OPT_WIDTH,
	OptionInfo + OPT_QUIET,
	OptionInfo + OPT_VERBOSE,
	OptionInfo + OPT_PROGRESS,
	OptionInfo + OPT_LOGGING,
	OptionInfo + OPT_ESC,
	OptionInfo + OPT_IO,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	0
};

static const InfoOption_t * option_tab_cmd_VERSION[] =
{
	OptionInfo + OPT_SECTIONS,
	OptionInfo + OPT_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_HELP[] =
{

	0
};

static const InfoOption_t * option_tab_cmd_TEST[] =
{

	0
};

static const InfoOption_t * option_tab_cmd_ERROR[] =
{
	OptionInfo + OPT_SECTIONS,
	OptionInfo + OPT_NO_HEADER,
	&option_cmd_ERROR_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_EXCLUDE[] =
{
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	0
};

static const InfoOption_t * option_tab_cmd_TITLES[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	0
};

static const InfoOption_t * option_tab_cmd_FIND[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_FIND_QUIET,
	OptionInfo + OPT_NO_HEADER,
	&option_cmd_FIND_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_SPACE[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_NO_HEADER,
	&option_cmd_SPACE_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_ANALYZE[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_ANALYZE_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_DUMP[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INODE,
	&option_cmd_DUMP_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_ID6[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	&option_cmd_ID6_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_LIST[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_MIXED,
	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	OptionInfo + OPT_ITIME,
	OptionInfo + OPT_MTIME,
	OptionInfo + OPT_CTIME,
	OptionInfo + OPT_ATIME,
	OptionInfo + OPT_TIME,
	&option_cmd_LIST_LONG,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_SECTIONS,

	0
};

static const InfoOption_t * option_tab_cmd_LIST_L[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_MIXED,
	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	OptionInfo + OPT_ITIME,
	OptionInfo + OPT_MTIME,
	OptionInfo + OPT_CTIME,
	OptionInfo + OPT_ATIME,
	OptionInfo + OPT_TIME,
	&option_cmd_LIST_LONG,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_SECTIONS,

	0
};

static const InfoOption_t * option_tab_cmd_LIST_LL[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_MIXED,
	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	OptionInfo + OPT_ITIME,
	OptionInfo + OPT_MTIME,
	OptionInfo + OPT_CTIME,
	OptionInfo + OPT_ATIME,
	OptionInfo + OPT_TIME,
	&option_cmd_LIST_LONG,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_SECTIONS,

	0
};

static const InfoOption_t * option_tab_cmd_LIST_A[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_MIXED,
	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	OptionInfo + OPT_ITIME,
	OptionInfo + OPT_MTIME,
	OptionInfo + OPT_CTIME,
	OptionInfo + OPT_ATIME,
	OptionInfo + OPT_TIME,
	&option_cmd_LIST_LONG,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_SECTIONS,

	0
};

static const InfoOption_t * option_tab_cmd_LIST_M[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_MIXED,
	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	OptionInfo + OPT_ITIME,
	OptionInfo + OPT_MTIME,
	OptionInfo + OPT_CTIME,
	OptionInfo + OPT_ATIME,
	OptionInfo + OPT_TIME,
	&option_cmd_LIST_LONG,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_SECTIONS,

	0
};

static const InfoOption_t * option_tab_cmd_LIST_U[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_MIXED,
	OptionInfo + OPT_UNIQUE,
	OptionInfo + OPT_SORT,
	OptionInfo + OPT_ITIME,
	OptionInfo + OPT_MTIME,
	OptionInfo + OPT_CTIME,
	OptionInfo + OPT_ATIME,
	OptionInfo + OPT_TIME,
	&option_cmd_LIST_LONG,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_SECTIONS,

	0
};

static const InfoOption_t * option_tab_cmd_FORMAT[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_FORMAT_VERBOSE,
	OptionInfo + OPT_SIZE,
	OptionInfo + OPT_SPLIT,
	OptionInfo + OPT_SPLIT_SIZE,
	OptionInfo + OPT_HSS,
	OptionInfo + OPT_WSS,
	OptionInfo + OPT_RECOVER,
	&option_cmd_FORMAT_INODE,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_FORMAT_TEST,
	&option_cmd_FORMAT_FORCE,

	0
};

static const InfoOption_t * option_tab_cmd_RECOVER[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	0
};

static const InfoOption_t * option_tab_cmd_CHECK[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_CHECK_VERBOSE,
	&option_grp_CHECK_LONG,
	&option_cmd_CHECK_REPAIR,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	0
};

static const InfoOption_t * option_tab_cmd_REPAIR[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_CHECK_VERBOSE,
	&option_grp_CHECK_LONG,
	&option_cmd_REPAIR_REPAIR,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	0
};

static const InfoOption_t * option_tab_cmd_EDIT[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_PART,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_EDIT_TEST,
	&option_cmd_EDIT_FORCE,

	0
};

static const InfoOption_t * option_tab_cmd_PHANTOM[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_cmd_PHANTOM_VERBOSE,
	OptionInfo + OPT_TEST,

	0
};

static const InfoOption_t * option_tab_cmd_TRUNCATE[] =
{
	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	OptionInfo + OPT_TEST,

	0
};

static const InfoOption_t * option_tab_cmd_ADD[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_RECURSE,
	OptionInfo + OPT_RDEPTH,
	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_IGNORE_FST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_VERBOSE_VERBOSE,
	OptionInfo + OPT_PROGRESS,
	OptionInfo + OPT_LOGGING,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_PSEL,
	OptionInfo + OPT_RAW,
	OptionInfo + OPT_ID,
	OptionInfo + OPT_NAME,
	OptionInfo + OPT_MODIFY,
	OptionInfo + OPT_REGION,
	OptionInfo + OPT_IOS,
	OptionInfo + OPT_ENC,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_REMOVE,
	&option_cmd_SYNC_TRUNC,
	OptionInfo + OPT_NEWER,
	OptionInfo + OPT_SYNC,
	OptionInfo + OPT_UPDATE,
	&option_cmd_ADD_OVERWRITE,

	0
};

static const InfoOption_t * option_tab_cmd_UPDATE[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_RECURSE,
	OptionInfo + OPT_RDEPTH,
	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_IGNORE_FST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_VERBOSE_VERBOSE,
	OptionInfo + OPT_PROGRESS,
	OptionInfo + OPT_LOGGING,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_PSEL,
	OptionInfo + OPT_RAW,
	OptionInfo + OPT_ID,
	OptionInfo + OPT_NAME,
	OptionInfo + OPT_MODIFY,
	OptionInfo + OPT_REGION,
	OptionInfo + OPT_IOS,
	OptionInfo + OPT_ENC,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_REMOVE,
	&option_cmd_SYNC_TRUNC,
	OptionInfo + OPT_NEWER,
	OptionInfo + OPT_SYNC,

	0
};

static const InfoOption_t * option_tab_cmd_SYNC[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_RECURSE,
	OptionInfo + OPT_RDEPTH,
	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_IGNORE_FST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_VERBOSE_VERBOSE,
	OptionInfo + OPT_PROGRESS,
	OptionInfo + OPT_LOGGING,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_PSEL,
	OptionInfo + OPT_RAW,
	OptionInfo + OPT_ID,
	OptionInfo + OPT_NAME,
	OptionInfo + OPT_MODIFY,
	OptionInfo + OPT_REGION,
	OptionInfo + OPT_IOS,
	OptionInfo + OPT_ENC,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_REMOVE,
	&option_cmd_SYNC_TRUNC,
	OptionInfo + OPT_NEWER,

	0
};

static const InfoOption_t * option_tab_cmd_EXTRACT[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_VERBOSE_VERBOSE,
	OptionInfo + OPT_PROGRESS,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_DEST,
	OptionInfo + OPT_DEST2,
	OptionInfo + OPT_ESC,
	OptionInfo + OPT_SPLIT,
	OptionInfo + OPT_SPLIT_SIZE,
	OptionInfo + OPT_TRUNC,
	OptionInfo + OPT_CHUNK_MODE,
	OptionInfo + OPT_CHUNK_SIZE,
	OptionInfo + OPT_MAX_CHUNKS,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_WDF,
	OptionInfo + OPT_ISO,
	OptionInfo + OPT_CISO,
	OptionInfo + OPT_WBFS,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_EXTRACT_UNIQUE,
	&option_cmd_EXTRACT_IGNORE,
	OptionInfo + OPT_REMOVE,
	OptionInfo + OPT_UPDATE,
	OptionInfo + OPT_OVERWRITE,
	OptionInfo + OPT_FAST,

	0
};

static const InfoOption_t * option_tab_cmd_REMOVE[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_VERBOSE_VERBOSE,
	OptionInfo + OPT_PROGRESS,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_REMOVE_UNIQUE,
	&option_cmd_REMOVE_IGNORE,
	OptionInfo + OPT_NO_FREE,

	0
};

static const InfoOption_t * option_tab_cmd_RENAME[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_cmd_RENAME_IGNORE,
	&option_cmd_RENAME_ISO,
	&option_cmd_RENAME_WBFS,

	0
};

static const InfoOption_t * option_tab_cmd_SETTITLE[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_cmd_RENAME_IGNORE,
	&option_cmd_RENAME_ISO,
	&option_cmd_RENAME_WBFS,

	0
};

static const InfoOption_t * option_tab_cmd_TOUCH[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_TOUCH_UNIQUE,
	&option_cmd_TOUCH_IGNORE,

	OptionInfo + OPT_NONE, // separator

	&option_cmd_TOUCH_ITIME,
	&option_cmd_TOUCH_MTIME,
	&option_cmd_TOUCH_CTIME,
	&option_cmd_TOUCH_ATIME,
	OptionInfo + OPT_SET_TIME,

	0
};

static const InfoOption_t * option_tab_cmd_VERIFY[] =
{
	OptionInfo + OPT_TITLES,
	OptionInfo + OPT_UTF_8,
	OptionInfo + OPT_NO_UTF_8,
	OptionInfo + OPT_LANG,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_AUTO,
	OptionInfo + OPT_ALL,
	OptionInfo + OPT_PART,
	&option_grp_MOD_WBFS_FORCE,
	&option_grp_MOD_WBFS_NO_CHECK,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_INCLUDE,
	OptionInfo + OPT_INCLUDE_PATH,
	OptionInfo + OPT_EXCLUDE,
	OptionInfo + OPT_EXCLUDE_PATH,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_QUIET,
	&option_grp_VERBOSE_VERBOSE,
	OptionInfo + OPT_PROGRESS,
	&option_cmd_VERIFY_LIMIT,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_PSEL,
	OptionInfo + OPT_RAW,
	&option_cmd_VERIFY_UNIQUE,
	&option_cmd_VERIFY_IGNORE,
	&option_cmd_VERIFY_REMOVE,
	OptionInfo + OPT_NO_FREE,
	&option_cmd_VERIFY_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_FILETYPE[] =
{
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_IGNORE_FST,
	OptionInfo + OPT_NO_HEADER,
	&option_cmd_FILETYPE_LONG,

	0
};


//
///////////////////////////////////////////////////////////////////////////////
///////////////                   InfoCommand                   ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoCommand_t CommandInfo[CMD__N+1] =
{
    {	0,
	false,
	false,
	"wwt",
	0,
	"wwt [option]... command [option|parameter|file]...",
	"Wiimms WBFS Tool (WBFS manager) : It can create, check, repair,"
	" verify and clone WBFS files and partitions. It can list, add,"
	" extract, remove and rename ISO images as part of a WBFS.",
	15,
	option_tab_tool
    },

    {	CMD_VERSION,
	false,
	false,
	"VERSION",
	0,
	"wwt VERSION [ignored]...",
	"Print program name and version and exit.",
	2,
	option_tab_cmd_VERSION
    },

    {	CMD_HELP,
	false,
	false,
	"HELP",
	"H",
	"wwt HELP [command] [ignored]...",
	"Print help and exit. If the first non option is a valid command name,"
	" then a help for the given command is printed.",
	0,
	option_tab_cmd_HELP
    },

    {	CMD_TEST,
	false,
	false,
	"TEST",
	0,
	"wwt TEST [ignored]...",
	"Test options: All options are allowed, some are printed.",
	0,
	option_tab_cmd_TEST
    },

    {	CMD_ERROR,
	false,
	false,
	"ERROR",
	"ERR",
	"wwt ERROR [error_code]",
	"Translate exit code to message or print a table with all error"
	" messages.",
	3,
	option_tab_cmd_ERROR
    },

    {	CMD_EXCLUDE,
	false,
	false,
	"EXCLUDE",
	0,
	"wwt EXCLUDE [additional_excludes]...",
	"Dump the internal exclude database to standard output (stdout).",
	2,
	option_tab_cmd_EXCLUDE
    },

    {	CMD_TITLES,
	false,
	false,
	"TITLES",
	0,
	"wwt TITLES [additional_title_file]",
	"Dump the internal title database to standard output (stdout).",
	4,
	option_tab_cmd_TITLES
    },

    {	CMD_FIND,
	false,
	true,
	"FIND",
	"F",
	"wwt FIND [wbfs_partition]...",
	"Find WBFS partitions and optionally print some geometric values.",
	6,
	option_tab_cmd_FIND
    },

    {	CMD_SPACE,
	false,
	false,
	"SPACE",
	"DF",
	"wwt SPACE [wbfs_partition]...",
	"Print disk space of WBFS partitions.",
	5,
	option_tab_cmd_SPACE
    },

    {	CMD_ANALYZE,
	false,
	false,
	"ANALYZE",
	"ANA",
	"wwt ANALYZE [wbfs_partition]...",
	"Analyze files and partitions for WBFS usage. Try to find old WBFS"
	" structures and make calculations for new WBFS.",
	4,
	option_tab_cmd_ANALYZE
    },

    {	CMD_DUMP,
	false,
	false,
	"DUMP",
	"D",
	"wwt DUMP [wbfs_partition]...",
	"Dump the data structure of WBFS partitions.",
	9,
	option_tab_cmd_DUMP
    },

    {	CMD_ID6,
	false,
	true,
	"ID6",
	"ID",
	"wwt ID6 [wbfs_partition]...",
	"List all ID6 of all discs of WBFS partitions.",
	10,
	option_tab_cmd_ID6
    },

    {	CMD_LIST,
	false,
	false,
	"LIST",
	"LS",
	"wwt LIST [wbfs_partition]...",
	"List all discs of WBFS partitions.",
	22,
	option_tab_cmd_LIST
    },

    {	CMD_LIST_L,
	false,
	false,
	"LIST-L",
	"LL",
	"wwt LIST-L [wbfs_partition]...",
	"List all discs of WBFS partitions. Same as 'LIST --long'.",
	22,
	option_tab_cmd_LIST_L
    },

    {	CMD_LIST_LL,
	false,
	false,
	"LIST-LL",
	"LLL",
	"wwt LIST-LL [wbfs_partition]...",
	"List all discs of WBFS partitions. Same as 'LIST --long --long'.",
	22,
	option_tab_cmd_LIST_LL
    },

    {	CMD_LIST_A,
	false,
	false,
	"LIST-A",
	"LA",
	"wwt LIST-A [wbfs_partition]...",
	"List all discs of all WBFS partitions. Same as 'LIST --long --long"
	" --auto'.",
	22,
	option_tab_cmd_LIST_A
    },

    {	CMD_LIST_M,
	false,
	false,
	"LIST-M",
	"LM",
	"wwt LIST-M [wbfs_partition]...",
	"List all discs of WBFS partitions in mixed view. Same as 'LIST --long"
	" --long --mixed'.",
	22,
	option_tab_cmd_LIST_M
    },

    {	CMD_LIST_U,
	false,
	false,
	"LIST-U",
	"LU",
	"wwt LIST-U [wbfs_partition]...",
	"List all discs of WBFS partitions in mixed view. Same as 'LIST --long"
	" --long --unique'.",
	22,
	option_tab_cmd_LIST_U
    },

    {	CMD_FORMAT,
	false,
	true,
	"FORMAT",
	"INIT",
	"wwt FORMAT file|blockdev...",
	"Initialize (=format) WBFS partitions and files. Combine with"
	" --recover to recover discs.",
	14,
	option_tab_cmd_FORMAT
    },

    {	CMD_RECOVER,
	false,
	false,
	"RECOVER",
	0,
	"wwt RECOVER [wbfs_partition]..",
	"Recover deleted discs of WBFS partitions.",
	8,
	option_tab_cmd_RECOVER
    },

    {	CMD_CHECK,
	false,
	false,
	"CHECK",
	"FSCK",
	"wwt CHECK [wbfs_partition]..",
	"Check WBFS partitions and print error listing. To repair WBFS"
	" partitions use the option '--repair modelist'.",
	12,
	option_tab_cmd_CHECK
    },

    {	CMD_REPAIR,
	false,
	false,
	"REPAIR",
	0,
	"wwt REPAIR [wbfs_partition]..",
	"Check WBFS partitions and repair errors. 'REPAIR' is a shortcut for"
	" 'CHECK --repair standard'.",
	12,
	option_tab_cmd_REPAIR
    },

    {	CMD_EDIT,
	false,
	false,
	"EDIT",
	0,
	"wwt EDIT [sub_command]...",
	"Edit slot and block assignments. Dangerous! Read docu!",
	4,
	option_tab_cmd_EDIT
    },

    {	CMD_PHANTOM,
	false,
	false,
	"PHANTOM",
	0,
	"wwt PHANTOM [sub_command]...",
	"Add phantom discs. Phantom discs have no content and only a header is"
	" written. This makes adding discs very fast and this is good for"
	" testing.",
	8,
	option_tab_cmd_PHANTOM
    },

    {	CMD_TRUNCATE,
	false,
	false,
	"TRUNCATE",
	"TR",
	"wwt TRUNCATE [wbfs_partition]..",
	"Truncate WBFS partitions to the really used size.",
	7,
	option_tab_cmd_TRUNCATE
    },

    {	CMD_ADD,
	false,
	true,
	"ADD",
	"A",
	"wwt ADD iso|wbfs|dir...",
	"Add Wii ISO discs to WBFS partitions.",
	36,
	option_tab_cmd_ADD
    },

    {	CMD_UPDATE,
	false,
	false,
	"UPDATE",
	"U",
	"wwt UPDATE iso|wbfs|dir...",
	"Add missing Wii ISO discs to WBFS partitions. 'UPDATE' is a shortcut"
	" for 'ADD --update'.",
	34,
	option_tab_cmd_UPDATE
    },

    {	CMD_SYNC,
	false,
	false,
	"SYNC",
	0,
	"wwt SYNC iso|wbfs|dir...",
	"Modify primary WBFS (REMOVE and ADD) until it contains exactly the"
	" same discs as all sources together. 'SYNC' is a shortcut for 'ADD"
	" --sync'.",
	33,
	option_tab_cmd_SYNC
    },

    {	CMD_EXTRACT,
	false,
	false,
	"EXTRACT",
	"X",
	"wwt EXTRACT id6[=dest]...",
	"Extract discs from WBFS partitions and store them as Wii ISO images.",
	36,
	option_tab_cmd_EXTRACT
    },

    {	CMD_REMOVE,
	false,
	false,
	"REMOVE",
	"RM",
	"wwt REMOVE id6...",
	"Remove discs from WBFS partitions.",
	20,
	option_tab_cmd_REMOVE
    },

    {	CMD_RENAME,
	false,
	false,
	"RENAME",
	"REN",
	"wwt RENAME id6=[new][,title]...",
	"Rename the ID6 of WBFS discs. Disc title can also be set.",
	18,
	option_tab_cmd_RENAME
    },

    {	CMD_SETTITLE,
	false,
	false,
	"SETTITLE",
	"ST",
	"wwt SETTITLE id6=title...",
	"Set the disc title of WBFS discs.",
	18,
	option_tab_cmd_SETTITLE
    },

    {	CMD_TOUCH,
	false,
	false,
	"TOUCH",
	0,
	"wwt TOUCH id6...",
	"Set time stamps of WBFS discs.",
	21,
	option_tab_cmd_TOUCH
    },

    {	CMD_VERIFY,
	false,
	false,
	"VERIFY",
	"V",
	"wwt VERIFY id6...",
	"Verify all discs of WBFS (calculate and compare SHA1 check sums) to"
	" find bad dumps.",
	25,
	option_tab_cmd_VERIFY
    },

    {	CMD_FILETYPE,
	false,
	true,
	"FILETYPE",
	"FT",
	"wwt FILETYPE filename...",
	"Print a status line for each source file.",
	4,
	option_tab_cmd_FILETYPE
    },

    {0,0,0,0,0,0,0,0}
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                     InfoUI                      ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoUI_t InfoUI =
{
	"wwt",
	CMD__N,
	CommandTab,
	CommandInfo,
	OPT__N_SPECIFIC,
	OPT__N_TOTAL,
	OptionInfo,
	OptionUsed,
	OptionIndex,
	OptionShort,
	OptionLong
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                       END                       ///////////////
///////////////////////////////////////////////////////////////////////////////

