
//---------------------------------"
// This file is generated by make."
// Any changes will be lost!"
//---------------------------------"

#define WWT_SHORT	"@@WWT-SHORT@@"
#define WWT_LONG	"@@WWT-LONG@@"
#define WIT_SHORT	"@@WIT-SHORT@@"
#define WIT_LONG	"@@WIT-LONG@@"
#define AUTHOR		"@@AUTHOR@@"

#define VERSION		"@@VERSION@@"
#define REVISION	"@@REV@@"
#define REVISION_NUM	@@REV-NUM@@
#define REVISION_NEXT	@@REV-NEXT@@

#define BINTIME		@@BINTIME@@
#define DATE		"@@DATE@@"
#define TIME		"@@TIME@@"
#define DATETIME	"@@DATE@@ @@TIME@@"

#define URI_REPOS	"@@URI-REPOS@@/"
#define URI_VIEWVC	"@@URI-VIEWVC@@/"
#define URI_HOME	"@@URI-HOME@@"
#define URI_DOWNLOAD	"@@URI-DOWNLOAD@@"

